name: yolo
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - mamba
  - python==3.9
  - pytorch=1.11.0=py3.9_cuda11.5_cudnn8.3.2_0
  - pytorch-lightning
  - torchvision
  - scipy
  - tensorboard
